### ISSUE TITLE
OTD no longer load after updating to 3.5.3

### ISSUE THREAD

**Issue by valkyr1esama** [dimdenGD/OldTweetDeck#223]
OldTweetdeck no longer load after updating to 3.5.3 from 3.4.0, just giving me infinite loading. I have removed and reinstalled it.

Went back to 3.4.0 also not working anymore. 

I am on Firefox stable or is it only working on Nightly/Dev edition now?

Thank you!

**Comment by dimdenGD** [comment]
Please include errors in console (F12)

**Comment by valkyr1esama** [comment]
I hope I got this correct

attempt to revive moduleraid failed TypeError: window[this.entrypoint] is not a function
    fillModules moz-extension://d8c35acd-3939-4958-8f2e-4ab3334bf0bf/build/inject.js:2
    r moz-extension://d8c35acd-3939-4958-8f2e-4ab3334bf0bf/build/inject.js:2
    n moz-extension://d8c35acd-3939-4958-8f2e-4ab3334bf0bf/build/inject.js:140
    setInterval handler* moz-extension://d8c35acd-3939-4958-8f2e-4ab3334bf0bf/build/inject.js:140
    <anonymous> moz-extension://d8c35acd-3939-4958-8f2e-4ab3334bf0bf/build/inject.js:140
    <anonymous> moz-extension://d8c35acd-3939-4958-8f2e-4ab3334bf0bf/build/inject.js:140
    <anonymous> moz-extension://d8c35acd-3939-4958-8f2e-4ab3334bf0bf/build/inject.js:140
    <anonymous> moz-extension://d8c35acd-3939-4958-8f2e-4ab3334bf0bf/build/inject.js:140


It's just keep increasing non-stop

**Comment by dimdenGD** [comment]
Try disabling BetterTweetDeck

**Comment by valkyr1esama** [comment]
It is no longer giving that error but still infinite loading =(

There are also multiple errors below with different last part of the URL.

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://abs.twimg.com/responsive-web/client-web/main.514cf9ba.js. (Reason: CORS request did not succeed). Status code: (null).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://abs.twimg.com/responsive-web/client-web/vendor.1decd5ea.js. (Reason: CORS request did not succeed). Status code: (null).

**Comment by dimdenGD** [comment]
Please screenshot entire log

**Comment by valkyr1esama** [comment]
Here you go

![firefox_2024-03-31_00-36-50](https://github.com/dimdenGD/OldTweetDeck/assets/165482849/cb68a7e5-8c08-47c8-95b8-2f2abe858926)

**Comment by valkyr1esama** [comment]
Oh it loads suddenly after I just left it alone for quite a long time

Another error in the log, not sure if it is an issue and increasing as well

![firefox_2024-03-31_00-44-55](https://github.com/dimdenGD/OldTweetDeck/assets/165482849/f42a0ab0-7234-4797-928c-18d283618056)
![firefox_2024-03-31_00-46-07](https://github.com/dimdenGD/OldTweetDeck/assets/165482849/ebbe070d-fe90-4703-bf94-7212ceea74ac)

**Comment by shapman88** [comment]
I had the same thing happen last night, and now I am rate limited even though the bypass was turned on. Unfortunately, I don't have access to the logs on the computer as I don't have access to that computer right now.

![image](https://github.com/dimdenGD/OldTweetDeck/assets/91422602/0f89895b-64f2-48d3-8cbe-6d409f01874c)

**Comment by httpsnk** [comment]
I have the same issue. My OTD won't open unless I tried to open the page while still open console (F12) and refresh it again.

**Comment by boilinabag** [comment]
FWIW, I got this login hang up on the past rev yesterday, and rolled back to 3.3,  it logged right in. i'm using it now. will try your new rev tomorrow. no log out issues either... thanks.

**Comment by jlitz** [comment]
I was getting auto disconnected from twitter a lot ever hour or so last couple days. I just installed the update a few hours ago and so far problem is gonel
